CMSgov/qpp-submissions-docs

- src/components/app.jsx
Genevieve and I were on a call with athenahealth last week, including members of their development team, and they did not realize there is a public sandbox available. They thought they could only access the API via the Swagger UI. Since qpp-submissions-docs is the main portal for developer documentation, I want to update the copy around the interactive API reference to make it more explicit that you can access the API endpoints via the command line directly.
> Make public sandbox more explicit

- src/components/app.jsx
- src/components/privatebeta.jsx
-google form is no longer being used to collect requests for api key; updated copy to let reader know to email QPP service center to request one
-made some other small copy changes, as per jonathan sullivan's comments here: https://confluence.cms.gov/pages/viewpage.action?pageId=68731604
> QPPA-853 make copy changes about private beta in dev docs

- src/components/app.jsx
a hardcoded domain means the link only ever leads to the prod site - using a relative path makes it easy to both develop and have the correct domain in production.
> uses relative schemas link

- src/components/tutorials/advanced-tutorial.jsx
- src/components/tutorials/basic-tutorial.jsx
We forgot to update these example url paths when we removed the versioning in the url. These are just static content to illustrate what api requests look like in the basic and advanced tutorials (they're not used in any programmatic fashion), but it's good to be correct.
> updates old /v1/x urls to /x

- src/components/api-reference/schemas/submissions.jsx
- src/components/app.test.js
- src/components/developer-preview.js
- src/components/introduction.js
- src/components/routes.jsx
Small fixes to Dev Docs content:
1. QPPA-1097 - change the text 'getting a key' to 'developer preview'
2. QPPA-1098 - add link to swagger under 'topics'
3. QPPA-1099 - embed youtube video in 'developer preview'
4. QPPA-1101 - change order of objects under 'references' to de-emphasize the submission object
5. QPPA-1072 - add sentence to 'submissions' page to make clear that the object is 'shared' - also change to 'submissions' (plural) to be consistent with the other pages
> Ivanang make updates to dev docs sept 2017

- src/components/tutorials/advanced-tutorial.js
Forgot to remove the narrow screen warning for the advanced tutorial - doing so here
> remove obsolete narrow screen warning

- src/components/tutorials/common/steps/advanced-3.js
- src/components/tutorials/common/steps/advanced-5.js
- src/components/tutorials/common/steps/basic-3.js
We have a couple example code tabs that are blank, which is possibly confusing for folks using the tutorial - we kept them blank previously since there was logic associated with having the two tabs. Since that logic has been removed, we can get rid of the blank tabs that look like this:
the 'after' for the three blank tabs:
> remove unused example code tabs

- src/components/api-reference/schemas/submissions.js
1. Clarify on https://cmsgov.github.io/qpp-submissions-docs/submissions that NPI is only writable when entityType == individual
2. Also get rid of details about TIN and NPIs having to start with 0
a complement to @kencheeto 's PR in the appcode - https://github.com/CMSgov/qpp-submissions-api/pull/601
> Clarify when npi is writable

- package-lock.json
- package.json
- src/components/api-reference/example-docs.js
we are getting this error intermittently when running tests: https://reactjs.org/warnings/refs-must-have-owner.html
I ran `npm ls react` to see what packages were requiring React - looks like `react-file-download` also may include a copy of React. The author published a new version of the library called `js-file-download` since the original didn't use React at all anyway, which appears to fix the build.
```sh
kenshiro15:qpp-submissions-docs kencheeto$ npm ls react
qpp-submissions-docs@0.0.0 /Users/kencheeto/nava/qpp-submissions-docs
├─┬ @cmsgov/design-system-core@1.0.1
│ └── react@15.6.1  deduped
├── react@15.6.1
└─┬ react-file-download@0.3.2
└── react@0.14.9
```
> try to fix refs must have owner warning

- src/components/api-reference/scoring.js
Adding ACI Measurement Set ID to ACI and IA:
> QPPMA-1361: Adding ACI/IA Measurement Set ID

- src/components/api-reference/schemas/measurements.js
https://jira.cms.gov/browse/QPPA-1482
Added descriptions for difference between registry and non-registry single and multi perf rate. Also updated the multi perf rate documentation for performance and reporting rates which was incorrect before.
> QPPA-1482 Update documentation for registry single and multi perf rate

- src/components/tutorials/advanced-tutorial.js
This mention of DELETE for each resource is slightly inaccurate because DELETE /submissions is not currently allowed and will be removed:
so removing that language here:
> fix inaccuracy for DELETE /submissions

- src/components/api-reference/scoring.js
Adding CPC+ Metadata and Messages to Scoring page.
> Add CPC+ Metadata to Scoring Docs

- package-lock.json
In order to make #99 simpler, separate this out.
* Run `npm install` with npm 6.2.0 to update package-lock.json.
* Run `npm dedupe`
* Output was:
* removed 64 packages, moved 6 packages and audited 12835 packages in 7.892s
This is meant to be a no-op in package versions, however npm has changed how it stored dependency versions in package-lock.json. None of the "version" lines (which determine what was actually installed) in package-lock.json have changed as far as I can see.
> Run `npm install` and `npm dedupe` with npm 6.2.0

- src/components/developer-preview.js
Two additional TINs were added to https://confluence.cms.gov/display/QPPARCH/TIN+to+Provider+Relationships. I am updating this page to reflect that.
> add tins to special scoring section of dev preview

- src/components/api-reference/schemas/measurements.js
Adding reportingRate to nonProportion metric type. Also removed final instances of ACI (switched to PI). Also updated reportingRate descriptions to align with "data completeness" terminology.
There's no ticket for this, but reflects info for changes in announcement here: https://groups.google.com/forum/#!topic/qpp-apis/WqNS1V2sTQY
> Update to nonprop and PI

- src/components/tutorials/qualified-registries-and-qcdrs.js
Missed a section that should be removed in our latest update for the new dev docs, see confluence page to confirm and review what's there vs what's on the dev docs as is please
> Remove old text from dev docs

- package-lock.json
- package.json
Per QPPA-3877, updating bootstrap. `3.3.7` -> `3.4.1`
> QPPA-3877: Update bootstrap dependency

- src/components/tutorials/qualified-registries-and-qcdrs.js
Updates the descriptions for the POST and GET endpoints of /submissions
new POST /submission:
new GET /submission:
> QPPA-4224 Updating explanations for POST /submissions

- src/components/references/references.js
[QPPA-4327](https://jira.cms.gov/browse/QPPA-4327)
- removed QRDA III to JSON Conversion Tool for Developer Preview Testing
> QPPA-4327 - removed QRDA III to JSON Conversion Tool for Developer Preview Testing

- src/app/components/topics/introduction.tsx
Removed Google groups reference on introduction page.
Google groups have not been changed in a while.
Tested and working locally.
> QPPA-4674: Removed Google groups reference on introduction page.

- .snyk
- package-lock.json
snyk is currently flagging react-scripts 3.4.4 as a vulnerability and is trying to upgrade it to v4.0.0, which breaks the application. This PR as a .snyk file that ignores the effected folders.
unit tests passing, tested locally.
> QPPA-4756: added snyk file to ignore react-scripts v4 upgrade

- src/app/components/guides/submitting-to-submissions-api.tsx
- src/app/components/references/submissions.tsx
Removes bad characters on the Submission reference page and duplicate text on the submitting guide.
Tests and Linter passing locally.
> Removing bad and duplicate text

- .gitignore
- .snyk
- package-lock.json
- package.json
- src/styles/vendor/qpp-style.css
- tsconfig.json
Updated react-scripts, eslint, babel, and jest node packages to latest versions as a security upgrade.
Also added .eslintcache to gitignore until the file is removed in a later react-scripts version.
> QPPA-4750: Updated node packages, gitignore file

- src/app/components/references/references.tsx
Added link to Scoring API documentation under the references page.
The Scoring API was mentioned but no links to the swagger docs were provided.
Ran app locally and verified link and updated timestamp.
> Added link to Scoring API docs

- src/app/components/topics/change-log.tsx
Updated changelogs: PracticeDetails for pcf submissions to accept 0 to 1 tin instead of 0 to many.
> QPPA-5494 practiceDetails to have tin instead of tins

- src/app/components/references/data.ts
- src/app/components/references/measurements.tsx
Adds calculation for reportingRate to the Description for the Non-Proportion Measurements.
https://cmsgov.github.io/qpp-submissions-docs/measurements#non-proportion-measurements
The reporting rate, ranging from zero to one-hundred and representing a percentage, is equal to 100 * ( ( observationInstances + denominatorException + numeratorExclusion ) / denominator ). This is also referred to as data completeness.
- This change includes a more detailed description of the reporting rate by including the API-side calculation of the metric.
- This change creates more consistency with the description provided in other measurement types (eg. Single-Performance Rate and Multi-Performance Rate)
https://jira.cms.gov/browse/QPPA-5994
> QPPA-5944: Updates reportingRate description of non-proportion measurements

- src/app/components/topics/change-log.tsx
Adds update to changelog regarding recent validation changes to performanceRate in Submissions API for registrySinglePerformanceRate and registryMultiPerformanceRate metric types.
https://jira.cms.gov/browse/QPPA-5995
> QPPA-5995 - adds performanceRate validation changes to change log

- src/app/components/references/data.ts
---
https://jira.cms.gov/browse/QPPA-8388
---
---
---
---
---
> QPPA-8388: Restore table for multi rate stratum

- src/app/components/guides/getting-started-with-oauth.tsx
---
https://jira.cms.gov/browse/QPPA-8374
---
---
---
---
> QPPA-8374: updates test data service link

- package-lock.json
- package.json
- src/styles/_global.scss
---
Adds fontawesome package so qpp-style loads font family correctly. This was a necessary change after vite upgrade.
---
---
---
> QPPA-0000: Adds fontawesome package so qpp-style loads font family correctly

- src/app/components/references/data.ts
- src/app/components/references/measurements.tsx
https://jira.cms.gov/browse/QPPA-9720
---
add case count prop to multi perf rate mm
---
---
---
> QPPA-9720: add case count field 
