public/index.html

Adding Google Analytics tracking code to https://cmsgov.github.io/qpp-submissions-docs/ and child pages.

QPPA-738 - add google analytics tracking code

---

README.md
src/components/app.jsx

put the command first, then discuss details 😅

clearer deploy instructions

---

src/components/privatebeta.jsx

Adding the API endpoint to the private beta info page!!

Ivanang add url for private beta endpoint

---

public/index.html

somehow, the ga tag disappeared from this file. this PR is to add it back in.

add google analytics tag back in

---

.gitignore
.travis.yml
README.md
package-lock.json
package.json

we're converging on npm instead of yarn since npm 5 brought big improvements; i also updated some outdated npm packages.

updates docs to use npm instead of yarn, updates packages

---

src/components/api-reference/api-reference.jsx
src/components/api-reference/schemas/benchmarks.jsx
src/components/api-reference/schemas/measurement-sets.jsx
src/components/api-reference/schemas/measurements.jsx
src/components/api-reference/schemas/submission.jsx
src/components/app.jsx
src/components/developer-preview.jsx
src/components/tutorials/advanced-tutorial.jsx
src/components/tutorials/basic-tutorial.jsx

My first PR for the QPP Submission API docs.  Please give this a review and let me know if there are problems.  Happy to do this together on Monday as well.

lots of minor copy changes

---

README.md

adds note to check that we're always on latest master before deploying, as well as that you'll have to be a collaborator on the repo.

Adds note about pulling latest master

---

src/components/api-reference/schemas/measurement-sets.jsx
src/components/tutorials/common/steps/advanced-2.js
src/components/tutorials/common/steps/basic-2.js

On the tutorial:
On the schema:

Adds documentation about created/updated at times to a mSet

---

src/components/api-reference/schemas/measurement-sets.jsx

Made this change last sprint - https://jira.cms.gov/browse/QPPA-810 - but dev docs weren't updated.

Update docs to say perf start and end are required

---

src/components/footer.js

widens the footer to match the main content. sorry about the changing background color of the main content - this pr doesn't touch that, it's the gif 🙇

make footer as wide as main content

---

src/components/developer-preview.js
src/components/introduction.js

The developer preview is being extended until December 15th!
Reviewer: @kencheeto

Copy edits for developer preview

---

src/components/api-reference/scoring.js

- Add measurementSetPicked in measurement set metadata descriptions for IA, ACI, and Quality
- Add maxFinalScore in submission metadata description
- Add maxContribution to quality score measurement set metadata

QPPQS-688 Add measurementSetPicked, maxFinalScore and maxContribution metadata descriptions

---

src/components/introduction.js

updated deadline from march 31st to april 3rd per new CMS deadline for submission. no ticket, but changes per the comms sent out yesterday.

update new mips close deadline

---

src/components/api-reference/schemas/measurements.js
src/components/api-reference/scoring.js

Updated docs to include CAHPS and All Cause Readmission measurements.

[QPPSF-2159] ACR and CAHPS measurements

---

src/components/api-reference/scoring.js

QPPSF-2231: Update metadata field description for totalBonusPoints, totalMeasurementPoints and totalDecileScore

QPPSF-2231: Update metadata field description for totalBonusPoints, totalMeasurementPoints and totalDecileScore

---

src/components/developer-preview.js
src/components/introduction.js
src/components/rate-limiting.js

Update dev docs for close of submission window (seems like it would've been better to update this earlier, but I guess it's used much less than the email list?)
Jira ticket: https://jira.cms.gov/browse/QPPA-2848
Screenshots of new copy (links have been tested): 
Reviewer: @sarahnw

[QPPA-2848] Update dev docs for close of submission window

---

oauth_sample/.gitignore
oauth_sample/README.md
oauth_sample/cache.js
oauth_sample/config.js
oauth_sample/config.js.example
oauth_sample/package-lock.json
oauth_sample/package.json
oauth_sample/pkce.js
oauth_sample/server.js

This is an upload of the Auth service's sample OAuth app.  Top level `README.md` contains information on how to use this.

Adding QPP OAuth sample application to submissions-docs repo

---

src/components/developer-preview.js
src/components/tutorials/getting-started-with-oauth2.js

This adds links to the Data Faker Swagger page. Removed TODOs.

QPPA-3072: Part 2 - Add Data Faker Swagger URL

---

src/components/tutorials/authorization-and-authentication.js

Verbiage was outdated. OAuth is in prod now. Woo!

QPPA-3631: Change to say we support OAuth

---

src/components/developer-preview.js

Motivation for change
Remove Special Scoring Scenarios from developer preview.
What is being changed
src/components/developer-preview.js
Release checklist:
Tasks that must be done prior to merging this PR, including testing.
Associated JIRA tickets:
* https://jira.cms.gov/browse/QPPSF-5571

QPPSF-5571:Remove Special Scoring Scenarios

---

src/components/app.test.js
src/components/change-log.js
src/components/routes.js
src/styles/app.css

[QPPA-4182](https://jira.cms.gov/browse/QPPA-4182)
- added `change log` section

QPPA-4182 - added `change log` section

---

src/components/topics/announcements.js

[QPPA-4381](https://jira.cms.gov/browse/QPPA-4381)
- added `announcements` section

QPPA-4381 - added `announcements` section

---

src/components/references/references.js
src/components/routes.js

[QPPA-4395](https://jira.cms.gov/browse/QPPA-4395)
- added content to `reference` section

QPPA-4395 - added content to `reference` section

---

src/components/resources/frequently-asked-questions.js
src/styles/app.css

[QPPA-4382](https://jira.cms.gov/browse/QPPA-4382)
- added faq section

QPPA-4382 - added faq section

---

src/components/resources/frequently-asked-questions.js
src/components/terms-of-service.js

[QPPA-4384](https://jira.cms.gov/browse/QPPA-4384)
- updated terms of service

QPPA-4384 - updated terms of service

---

src/components/resources/frequently-asked-questions.js
src/components/resources/help.js

[QPPA-4383](https://jira.cms.gov/browse/QPPA-4383)
- added help section

QPPA-4383 - added help section

---

src/components/developer-preview.js

[QPPA-4272](https://jira.cms.gov/browse/QPPA-4272)
- updated content on developer preview tab

QPPA-4272 - updated content on developer preview tab

---

src/components/developer-preview.js
src/components/resources/frequently-asked-questions.js
src/components/resources/help.js
src/components/topics/announcements.js

updates per michelle

---

oauth_sample/.gitignore
oauth_sample/README.md
oauth_sample/cache.js
oauth_sample/config.js.example
oauth_sample/package-lock.json
oauth_sample/package.json
oauth_sample/pkce.js
oauth_sample/server.js
src/app/components/guides/getting-started-with-oauth.tsx
src/app/components/references/data.ts
src/app/components/references/measurements.tsx
src/app/components/topics/developer-preview.tsx
src/shared/data-model-table.tsx
src/styles/_global.scss

[QPPA-4465](https://jira.cms.gov/browse/QPPA-4465)

QPPA-4465  - bug fixes

---

src/app/components/app.tsx

[QPPA-4286)](https://jira.cms.gov/browse/QPPA-4286)
- updated link to open externally

QPPA-4286) - updated link to open externally

---

src/app/components/topics/introduction.tsx

Updated introduction page wording and changed endpoints from links to highlighted code.
The links were misleading, as the endpoints were not meant to be clicked.
Ran locally.

QPPA-4661: Updated introduction page endpoints

---

src/app/components/guides/qualified-registries-and-qcdrs.tsx
src/app/components/topics/change-log.tsx

Added new measures changes to changelog and cleaned up the QCDR tab

QPPA-4588: Added new measures changes to changelog

---

src/app/components/references/scoring.tsx

Removes unnecessary link from the scoring page.

QPPA-5388: remove test link

---

src/app/components/references/benchmarks.tsx
src/app/components/references/data.ts

fix: general fixes

---

src/app/components/references/data.ts

Added entityId to the input example on the Submissions page
removed measureSet from the Mset page

QPPA-5468 fixed input examples

---

src/app/components/topics/change-log.tsx

Adds new row to change log page to reflect program query params feature on the `GET /submissions/{id}/score` endpoint.
Tested with existing test suite.

QPPA-5381: updates change log to explain program query params feature

---

src/app/components/footer.tsx
src/envConfig.ts

Adds CCSQ Support Central Link to global footer.
- Ran test suite
- Manually tested new link

QPPA-5905: Adds CCSQ Link to Footer

---

src/app/components/topics/change-log.tsx

2 changelog updates were needed:
- end of CPC+ program
- changes to PCF program submissions
See screenshot from local app instance for details.
- local testing and test suite
https://jira.cms.gov/browse/QPPA-6125
https://jira.cms.gov/browse/QPPA-6638

QPPA-6638 & QPPA-6125: Changelog updates for CPC+ and PCF programs

---

src/app/components/topics/change-log.tsx

- Updates change log with details regarding Y6 special scoring scenarios
- Ran local instance of application
- ran test suite
https://jira.cms.gov/browse/QPPA-6705

QPPA-6705: Update change log for Y6 special scoring scenarios

---

src/app/components/guides/advanced-tutorial.tsx
src/app/components/guides/basic-tutorial.tsx
src/app/components/guides/data.ts
src/app/components/references/data.ts
src/app/components/references/json/submission-example-aci.json
src/app/components/references/json/submission-example-ia.json
src/app/components/references/json/submission-example-quality.json
src/app/components/references/scoring.tsx

- Dev Docs examples should be updated for PY 2022
- Tested Locally
- Ran test suite
QPPA Ticket:
https://jira.cms.gov/browse/QPPA-6707

QPPA-6707: Update tutorials and other pages for PY 2022

---

src/app/components/topics/change-log.tsx

Update changelog for APP submissions tutorial changes
- verified working locally
- ran test suite

QPPA-6716: Update changelog for APP submissions tutorial changes

---

src/app/components/topics/change-log.tsx

Create changelog entry for strata validation.
- verified locally
- ran test suite
https://jira.cms.gov/browse/QPPA-6895

QPPA-6895: Create changelog entry for strata validation

---

src/app/components/resources-and-support/frequently-asked-questions.tsx

added faq section

---

src/app/components/resources-and-support/frequently-asked-questions.tsx

- updates date field for changes in this PR: https://github.com/CMSgov/qpp-submissions-docs/pull/259

QPPA-6949 updates date field at top of page

---

src/app/components/resources-and-support/frequently-asked-questions.tsx

https://jira.cms.gov/browse/QPPA-7016

QPPA-7016: Adds PI_PCHDRR Bonus Measures Issue to FAQ

---

package-lock.json
package.json

---
https://jira.cms.gov/browse/QPPA-7890
---
---
---
---

QPPA-7890: fix snyk severe vulns by bumping react-code-blocks package

---

src/app/components/references/benchmarks.tsx
src/app/components/references/data.ts
src/app/components/references/json/submission-example-aci.json
src/app/components/references/json/submission-example-ia.json
src/app/components/references/json/submission-example-quality.json
src/app/components/references/scoring.tsx
src/app/components/topics/announcements.tsx

---
https://jira.cms.gov/browse/QPPA-7967
---
---
---
---
---

QPPA-7967: Add Y7 updates

---

src/app/components/guides/advanced-tutorial.tsx
src/app/components/guides/basic-tutorial.tsx
src/app/components/guides/data.ts
src/app/components/guides/getting-started-with-oauth.tsx

---
https://jira.cms.gov/browse/QPPA-7725
---
---
---
---
---

QPPA-7725: Y7 updates tutorials and oauth

---

src/app/components/resources-and-support/frequently-asked-questions.tsx
src/app/components/topics/change-log.tsx

---
https://jira.cms.gov/browse/QPPA-7953
---
---
---
---
---

QPPA-7953: Update Changelog and FAQ for Y7

---

src/app/components/guides/data.ts
src/app/components/guides/mvp-submissions.tsx
src/app/components/references/data.ts
src/app/components/references/measurements.tsx
src/app/components/topics/change-log.tsx
src/app/routes.ts

---
Updates to submission docs to create new multi-strata types, new schema for QCDR measures and MVP submission tutorial.
---
---
- [X ] 📝 Documentation Update
---
- [X ] 🙅 no, because they aren't needed
---
---
---
* For Chromium users: https://chrome.google.com/webstore/detail/gifs-for-github/dkgjnpbipbdaoaadbdhpiokaemhlphep
* For Firefox users: https://addons.mozilla.org/en-US/firefox/addon/gifs-for-github
* After installing the extension, click on the "GIF" button in the comment box and search for a gif that describes your PR!

QPPA-7965 - Updates for MVP Submissions

---

src/app/components/resources-and-support/frequently-asked-questions.tsx

---
https://jira.cms.gov/browse/QPPA-8140
---
update faq page to remove the issue which was fixed.
---
---
---
---

QPPA-8140: update faq page

---

src/app/components/resources-and-support/frequently-asked-questions.tsx

---
https://jira.cms.gov/browse/QPPA-8125
---
Updated MPV FAQ to resolved
---
---
---
---

QPPA-8125: Updated MPV FAQ to resolved

---

package-lock.json
package.json
src/app/components/footer.tsx
src/app/components/guides/advanced-tutorial.tsx
src/app/components/guides/authorization-and-authentication.tsx
src/app/components/guides/basic-tutorial.tsx
src/app/components/guides/getting-started-with-oauth.tsx
src/app/components/guides/qualified-registries-and-qcdrs.tsx
src/app/components/guides/submitting-to-submissions-api.tsx
src/app/components/left-nav.tsx
src/app/components/notFound/not-found.tsx
src/app/components/references/benchmarks.tsx
src/app/components/references/error-codes.tsx
src/app/components/references/measurement-sets.tsx
src/app/components/references/measurements.tsx
src/app/components/references/references.tsx
src/app/components/references/scoring.tsx
src/app/components/references/submissions.tsx
src/app/components/resources-and-support/frequently-asked-questions.tsx
src/app/components/resources-and-support/help.tsx
src/app/components/resources-and-support/terms-of-service.tsx
src/app/components/topics/announcements.tsx
src/app/components/topics/change-log.tsx
src/app/components/topics/developer-preview.tsx
src/app/components/topics/introduction.tsx
src/styles/_global.scss

https://jira.cms.gov/browse/QPPA-9269
---
Before:
After:
---
---
---
---

QPPA-9269: update design systems to v10

---

oauth_sample/package-lock.json
oauth_sample/package.json

https://jira.cms.gov/browse/QPPAUTH-3357
---
---
---
---

QPPAUTH-3357 Address security vulnerabilities in dependencies

---

src/app/components/references/data.ts
src/app/components/references/measurements.tsx
src/shared/link-to-id.tsx

https://jira.cms.gov/browse/QPPA-10258
---
---
---
---
---

QPPA-10258: fix hashlinks
